{% set name = "qiskit-experiments" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-experiments-{{ version }}.tar.gz
  sha256: 32106088d9c5a18e1db037c560c648fce4a0cc22a9ce25c10218b90c846a9f4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base >=3.4
    - numpy >=1.17
    - python >=3.7
    - qiskit-ibmq-provider >=0.16.0
    - qiskit-terra >=0.20.1
    - scipy >=1.4
    - uncertainties

test:
  imports:
    - qiskit_experiments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-experiments
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: https://qiskit.org/documentation/

extra:
  recipe-maintainers:
    - BastianZim
