{% set name = "qiskit-experiments" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-experiments-{{ version }}.tar.gz
  sha256: 7ddd72224d5394072b0683192e97b5981f629b20aeeb5c609dba0941e1cc98fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - qiskit-dynamics >=0.3.0
    - rustworkx
    - lmfit
    - matplotlib-base >=3.4
    - numpy >=1.17
    - python >=3.7
    - qiskit-ibm-experiment >=0.2.5
    - qiskit-terra >=0.22
    - scipy >=1.4
    - uncertainties

test:
  imports:
    - qiskit_experiments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-experiments
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: https://qiskit.org/documentation/

extra:
  recipe-maintainers:
    - BastianZim
